const docentes = [
    {
        nombres: "Jose Ruben",
        apellidos: "Clemente Corzo",
        matricula: "100020762",
        grado_academico: "Lic. En Ingenieria en Desarrollo de Software",
        numero_plaza: "123456789",
        numero_contrato: "123456789",
        direccion: "C. San Bernardino #261 Fraccionamiento Campanario",
        telefono: "9612215796",
        correo_institucional: "jose.clemente48@unach.mx",
    },

    {
        nombres: "Maria Fernanda",
        apellidos: "Gomez Lopez",
        matricula: "100035180",
        grado_academico: "Mtra. en Ciencias de la Computación",
        numero_plaza: "987654321",
        numero_contrato: "987654321",
        direccion: "Av. Central Sur #1500 Colonia Centro",
        telefono: "9613450123",
        correo_institucional: "maria.gomez@unach.mx",
    },
    {
        nombres: "Carlos Alberto",
        apellidos: "Ruiz Hernandez",
        matricula: "100042915",
        grado_academico: "Dr. en Sistemas de Información",
        numero_plaza: "112233445",
        numero_contrato: "112233445",
        direccion: "Blvd. Belisario Domínguez #3000 Col. Magisterial",
        telefono: "9615678901",
        correo_institucional: "carlos.ruiz@unach.mx",
    },
    {
        nombres: "Ana Laura",
        apellidos: "Perez Jimenez",
        matricula: "100058763",
        grado_academico: "Ing. en Software",
        numero_plaza: "654321098",
        numero_contrato: "654321098",
        direccion: "C. Tulipanes #45 Fraccionamiento Jardines",
        telefono: "9617892345",
        correo_institucional: "ana.perez@unach.mx",
    },
    {
        nombres: "Javier Alejandro",
        apellidos: "Solis Torres",
        matricula: "100060349",
        grado_academico: "Lic. en Desarrollo de Software",
        numero_plaza: "246813579",
        numero_contrato: "246813579",
        direccion: "Av. Solidaridad #100 Colonia La Condesa",
        telefono: "9619012347",
        correo_institucional: "javier.solis@unach.mx",
    },
    {
        nombres: "Sofia Guadalupe",
        apellidos: "Mendez Cruz",
        matricula: "100071452",
        grado_academico: "Mtra. en Ingeniería de Software",
        numero_plaza: "135792468",
        numero_contrato: "135792468",
        direccion: "Privada Las Flores #20 Residencial del Sur",
        telefono: "9610123456",
        correo_institucional: "sofia.mendez@unach.mx",
    },
    {
        nombres: "Ricardo Emilio",
        apellidos: "Vargas Morales",
        matricula: "100083201",
        grado_academico: "Lic. en Ingeniería de Sistemas",
        numero_plaza: "808182838",
        numero_contrato: "808182838",
        direccion: "C. Olivos #15 Fraccionamiento Vista Hermosa",
        telefono: "9612345678",
        correo_institucional: "ricardo.vargas@unach.mx",
    },
    {
        nombres: "Adriana Cecilia",
        apellidos: "Ramos Soto",
        matricula: "100099514",
        grado_academico: "Dr. en Tecnologías de la Información",
        numero_plaza: "909192939",
        numero_contrato: "909192939",
        direccion: "Circuito de la Paz #50 Col. Montebello",
        telefono: "9614567890",
        correo_institucional: "adriana.ramos@unach.mx",
    },
    {
        nombres: "Luis Fernando",
        apellidos: "Diaz Castro",
        matricula: "100104677",
        grado_academico: "Ing. en Desarrollo de Software",
        numero_plaza: "505152535",
        numero_contrato: "505152535",
        direccion: "Av. Independencia #88 Colonia Obrera",
        telefono: "9616789012",
        correo_institucional: "luis.diaz@unach.mx",
    },
    {
        nombres: "Elena Patricia",
        apellidos: "Molina Reyes",
        matricula: "100115026",
        grado_academico: "Lic. en Informática",
        numero_plaza: "707172737",
        numero_contrato: "707172737",
        direccion: "C. Fresnos #33 Fraccionamiento Bugambilias",
        telefono: "9618901234",
        correo_institucional: "elena.molina@unach.mx",
    },
];

export default docentes;
